name: CI
description: 'CI workflow for the project. Check formatting and validate config file.'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  validate-config:
    name: ğŸ’… Validate Prettier Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ§ª Run configuration validation
        run: npm run test

      - name: ğŸ“ Check formatting
        run: npm run format:check
